package com.neuroforge.controller;

import com.neuroforge.dto.request.AiGenerateRequest;
import com.neuroforge.dto.response.ApiResponse;
import com.neuroforge.dto.response.AiSuggestionResponse;
import com.neuroforge.entity.AiAssistant;
import com.neuroforge.service.AiEngineService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/ai")
@SecurityRequirement(name = "BearerAuth")
@Tag(name = "NeuroForge AI Hub", description = "Endpoints for offline AI synthesis of User Stories, QA Test Matrices, Sprint Risk, and Code Reviews")
public class AiAssistantController {

    private final AiEngineService aiEngineService;

    public AiAssistantController(AiEngineService aiEngineService) {
        this.aiEngineService = aiEngineService;
    }

    @GetMapping("/assistants")
    @Operation(summary = "List Configured AI Assistants", description = "Retrieves active AI models and specialized domain agents")
    public ResponseEntity<ApiResponse<List<com.neuroforge.dto.response.AiAssistantResponse>>> getAssistants() {
        return ResponseEntity.ok(ApiResponse.ok("AI Assistants retrieved", aiEngineService.getAllAiAssistants()));
    }

    @GetMapping("/suggestions/assistant/{aiId}")
    @Operation(summary = "Get Suggestions by Assistant", description = "Retrieves historical suggestions generated by an AI assistant")
    public ResponseEntity<ApiResponse<List<AiSuggestionResponse>>> getSuggestionsByAssistant(@PathVariable Integer aiId) {
        return ResponseEntity.ok(ApiResponse.ok("AI Suggestions retrieved", aiEngineService.getSuggestionsByAssistant(aiId)));
    }

    @PostMapping("/generate")
    @PreAuthorize("hasAnyRole('SYSTEM_ADMIN', 'PROJECT_MANAGER', 'PRODUCT_OWNER', 'BUSINESS_ANALYST', 'SOFTWARE_ARCHITECT', 'DEVELOPER', 'QA_ENGINEER')")
    @Operation(summary = "Generate AI Suggestion (Offline / Online)", description = "Synthesizes User Stories, Gherkin Test Cases, Sprint Delivery Risk, or Code Review insights")
    public ResponseEntity<ApiResponse<AiSuggestionResponse>> generateSuggestion(@Valid @RequestBody AiGenerateRequest request) {
        AiSuggestionResponse suggestion = aiEngineService.generateSuggestion(request);
        return ResponseEntity.ok(ApiResponse.ok("AI generation completed successfully", suggestion));
    }
}
