export const ROLES = {
  SYSTEM_ADMIN: {
    key: 'SYSTEM_ADMIN',
    name: 'System Admin',
    description: 'System administration, user access, and compliance auditing',
    badgeColor: 'bg-rose-50 text-rose-700 border-rose-200',
    icon: 'Shield',
  },
  PROJECT_MANAGER: {
    key: 'PROJECT_MANAGER',
    name: 'Project Manager',
    description: 'Sprint planning, resource management, and team velocity',
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-200',
    icon: 'FolderKanban',
  },
  PRODUCT_OWNER: {
    key: 'PRODUCT_OWNER',
    name: 'Product Owner',
    description: 'Product vision, backlog prioritization, and release sign-off',
    badgeColor: 'bg-amber-50 text-amber-800 border-amber-200',
    icon: 'Target',
  },
  BUSINESS_ANALYST: {
    key: 'BUSINESS_ANALYST',
    name: 'Business Analyst',
    description: 'Requirements engineering, user stories, and acceptance criteria',
    badgeColor: 'bg-emerald-50 text-emerald-800 border-emerald-200',
    icon: 'FileText',
  },
  SOFTWARE_ARCHITECT: {
    key: 'SOFTWARE_ARCHITECT',
    name: 'Software Architect',
    description: 'System architecture, ADRs, and technical standards',
    badgeColor: 'bg-purple-50 text-[#635BFF] border-purple-200',
    icon: 'Layers',
  },
  DEVELOPER: {
    key: 'DEVELOPER',
    name: 'Developer',
    description: 'Feature implementation, code delivery, and task tracking',
    badgeColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    icon: 'Code2',
  },
  QA_ENGINEER: {
    key: 'QA_ENGINEER',
    name: 'QA/Test Engineer',
    description: 'Test authoring, test execution runs, and defect management',
    badgeColor: 'bg-cyan-50 text-cyan-800 border-cyan-200',
    icon: 'CheckCircle2',
  },
  DEVOPS_ENGINEER: {
    key: 'DEVOPS_ENGINEER',
    name: 'DevOps Engineer',
    description: 'CI/CD pipelines, build automation, and environment deployments',
    badgeColor: 'bg-orange-50 text-orange-800 border-orange-200',
    icon: 'GitBranch',
  },
  CLIENT: {
    key: 'CLIENT',
    name: 'Client',
    description: 'Milestone visibility, progress review, and UAT sign-off',
    badgeColor: 'bg-teal-50 text-teal-800 border-teal-200',
    icon: 'Eye',
  },
};
